=== DevopsCBRE01/Actividad2LenguajeMarcas/dtd/Actividad02_DTD_Documentos.dtd
<!-- DTD Documentos -->
<!--Validamos DTD + XML desde la web https://www.xmlvalidation.com/ -->
<!-- Podemos tener varios "Documento"  -->
<!ELEMENT Documentos (Documento+)>
<!ELEMENT Documento (Libro?,Revista?,Periodico?)>
<!ATTLIST Documento id ID #REQUIRED><!--duda entre usar CDATA o ID -->
<!-- DTD Libro -->
<!ELEMENT Libro (Titulo,Capitulos,Indice,Sinopsis)>
<!ATTLIST Libro tipo_clase (novela | infantil | didactico) #REQUIRED>
<!ATTLIST Libro paginas CDATA #REQUIRED>
<!--<!ELEMENT Titulo (#PCDATA)>-->
<!ELEMENT Capitulos (Capitulo+)>
<!ELEMENT Capitulo (Contenido)>
<!ATTLIST Capitulo titulo CDATA #REQUIRED>
<!ATTLIST Capitulo paginas CDATA #REQUIRED>
<!--<!ELEMENT Contenido EMPTY>
<!ATTLIST Contenido enlace CDATA #REQUIRED>-->
<!--<!ELEMENT Indice (#PCDATA)>-->
<!ELEMENT Sinopsis (#PCDATA)>

<!-- DTD Revista -->
<!ELEMENT Revista (Titulo,Num_Revista,Indice,Secciones)>
<!ATTLIST Revista tipo_clase (informatica | corazon | coches | investigacion | otra) #REQUIRED>
<!ATTLIST Revista paginas CDATA #REQUIRED>
<!--<!ELEMENT Titulo (#PCDATA)>-->
<!ELEMENT Num_Revista (#PCDATA)>
<!--<!ELEMENT Indice (#PCDATA)>-->
<!ELEMENT Secciones (Seccion+)>
<!ELEMENT Seccion (Contenido)>
<!ATTLIST Seccion titulo CDATA #REQUIRED>
<!ATTLIST Seccion paginas CDATA #REQUIRED>
<!--<!ELEMENT Contenido EMPTY>
<!ATTLIST Contenido enlace CDATA #REQUIRED>-->


<!-- DTD Periodico -->
<!ELEMENT Periodico (SeccionesP)>
<!ATTLIST Periodico tipo_clase (nacionales | internacionales) #REQUIRED>
<!ATTLIST Periodico fecha_publicacion CDATA #REQUIRED>
<!ELEMENT SeccionesP (SeccionP+)>
<!ELEMENT SeccionP (Articulos)>
<!ATTLIST SeccionP tipo_seccion (economica | opinion | deportes | nacional | internacional) #REQUIRED>
<!ELEMENT Articulos (Articulo+)>
<!ELEMENT Articulo (Contenido)>
<!ATTLIST Articulo titulo CDATA #REQUIRED>
<!ATTLIST Articulo autor CDATA #REQUIRED>
<!--<!ELEMENT Contenido EMPTY>
<!ATTLIST Contenido enlace CDATA #REQUIRED>-->

<!--Elementos comunes-->
<!ELEMENT Contenido EMPTY>
<!ATTLIST Contenido enlace CDATA #REQUIRED>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Indice (#PCDATA)>

=== DevopsCBRE01/Actividad2LenguajeMarcas/schema/Actividad02_XML_Documentos_Schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Si usamos el dtd
<!DOCTYPE Documentos SYSTEM "Actividad02_DTD_Documentos.dtd">-->
<!--USAMOS  XSD-->
<Documentos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:noNamespaceSchemaLocation= "Actividad02_XSD_Documentos_Schema.xsd">
    <!-- Declaramos el XML para el tipo libro. -->
    <Documento id="L0001">
        <Libro tipo_clase="novela" paginas="200">
            <Titulo>xxxxxxxxx</Titulo>
            <Capitulos>
                <Capitulo titulo ="xxxxxA" paginas="100">
                    <Contenido enlace="https://xxxxA.com"/>
                </Capitulo>
                <Capitulo titulo ="xxxxxB" paginas="100">
                    <Contenido enlace="https://xxxxB.com"/>
                </Capitulo>
            </Capitulos>
            <!-- En indice incluimos código HTML para representar el indice. -->
            <Indice>
            <![CDATA[
                <html>
                    <head>
                        <title>Indice Libro1</title>
                    </head>
                </html>
            ]]>
            </Indice>
            <Sinopsis>sdfdfdfdfdfdfdfdfdf</Sinopsis>
        </Libro>
    </Documento>
    <!-- Declaramos el XML para el tipo Revista. -->
    <Documento id="R0001">
        <Revista tipo_clase="informatica" paginas="150">
            <Titulo>Hola!!!</Titulo>
            <Num_Revista>000024</Num_Revista>
            <Indice>
            <![CDATA[
                <html>
                    <head>
                        <title>Indice Revista</title>
                    </head>
                </html>
            ]]>
            </Indice>
            <Secciones>
                <Seccion titulo="Seccionxxxxx" paginas="3">
                     <Contenido enlace="https://xxxx.com"/>
                </Seccion>
                <Seccion titulo="SeccionxxRRR" paginas="5">
                     <Contenido enlace="https://RRRR.com"/>
                </Seccion>                
            </Secciones>
        </Revista>
    </Documento>
    <!-- Declaramos el XML para el tipo Periodico. -->
    <Documento id="P0001">
        <Periodico tipo_clase="internacionales" fecha_publicacion="2021-05-15">
            <SeccionesP>
                <SeccionP tipo_seccion="economica">
                    <Articulos>
                        <Articulo titulo="economia A" autor="Pepito">
                            <Contenido enlace="https://xxxxR.com"/>
                        </Articulo>
                        <Articulo titulo="economia B" autor="Juanito">
                            <Contenido enlace="https://xxxxDD.com"/>
                        </Articulo>                        
                    </Articulos>
                </SeccionP>
                <SeccionP tipo_seccion="opinion">
                    <Articulos>
                        <Articulo titulo="opinion A" autor="Pedrito">
                            <Contenido enlace="https://TTTTTT.com"/>
                        </Articulo>
                        <Articulo titulo="opinion B" autor="Josito">
                            <Contenido enlace="https://FFFFF.com"/>
                        </Articulo>                        
                    </Articulos>
                </SeccionP>                
            </SeccionesP>
        </Periodico>
    </Documento>
        <!-- Declaramos el XML para el tipo libro número 2. -->
    <Documento id="L0002">
        <Libro tipo_clase="novela" paginas="200">
            <Titulo>xxxxxxxxx</Titulo>
            <Capitulos>
                <Capitulo titulo ="xxxxxA" paginas="100">
                    <Contenido enlace="https://xxxxA.com"/>
                </Capitulo>
                <Capitulo titulo ="xxxxxB" paginas="100">
                    <Contenido enlace="https://xxxxB.com"/>
                </Capitulo>
            </Capitulos>
            <!-- En indice incluimos código HTML para representar el indice. -->
            <Indice>
            <![CDATA[
                <html>
                    <head>
                        <title>Indice Libro2</title>
                    </head>
                </html>
            ]]>            
            </Indice>
            <Sinopsis>sdfdfdfdfdfdfdfdfdf</Sinopsis>
        </Libro>
    </Documento>
</Documentos>
